type: openai
api_endpoint: http://10.10.0.3:9997/v1/chat/completions
request_header: {
  "Content-Type": "application/json; charset=UTF-8"
}
"request_body": {
  "model": "Qwen3-8B",
  "stream": true,
  "chat_template_kwargs": {
    "enable_thinking": false
  },
  "max_tokens": 40960,
  "temperature": 0.7,
  "messages": []
}
RAG:
  enable: false
  embedding:
    api_endpoint: http://127.0.0.1:8000/v1
    model: bge-m3
    api_key: empty
  top_k: 3
